version: '3.3'

services:
  redis_stage:
    image: 'bitnami/redis:latest'
    restart: always
    command: redis-server --save '' --appendonly no --loglevel warning --protected-mode no
    volumes:
      - hopehome_stage_cache:/data
  mysql_stage:
    image: mysql:latest
    environment:
      - MYSQL_ROOT_PASSWORD=12345678
    ports:
      - "5037:3306"
    volumes:
      - hopehome_stage_data:/var/lib/mysql
  api_stage:
    build:
      dockerfile: ./Dockerfile.api
      context: .
    restart: always
    environment:
      - DATABASE_URL=mysql://root:12345678@mysql/hopehome_stage_db
      - REDIS_URL=redis
      - SESSION_SECRET=sup3rs3cr3t
      - DEFAULT_PASSWORD=12345678
      - JWT_SECRET=32d07665.2022e4
      - PORT=8080
      - EMAIL=hopehome694@gmail.com
      - ADMIN_EMAIL=hopehome694@gmail.com
      - CLIENT_SECRET=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
      - CLIENT_ID=192320988067-mjrh21aa3ue5blqp2o0nng7tmjkrl971.apps.googleusercontent.com
      - REFRESH_TOKEN=1//04UZ1ijN8XWr7CgYIARAAGAQSNwF-L9IrZfZaL8W-vPx82Unfc0af8ilt9jrkNiB9F-SWBRiqfRtxNFRnYdkhJNrtX1DGDwNA1Pw
      - NODE_ENV=production
      - SALT=12
    ports:
      - "95:8080"
    depends_on:
      - mysql_stage
      - redis_stage
    volumes:
      - hopehome_stage_assets:/app/dist/apps/api/assets
  landing_stage:
    build:
      dockerfile: ./Dockerfile.landing
      context: .
    restart: always
    ports:
      - "93:3000"
    depends_on:
      - api_stage
volumes:
  hopehome_stage_cache:
    driver: local
  hopehome_stage_data:
    driver: local
  hopehome_stage_assets:
    driver: local
